<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            [
                'name' => 'Conakry',
                'slug' => 'conakry',
                'code' => 'GN001',
                'description' => 'Capitale de la Guinée, centre économique et politique',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Kankan',
                'slug' => 'kankan',
                'code' => 'GN002',
                'description' => 'Deuxième ville de Guinée, capitale de la Haute-Guinée',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Kindia',
                'slug' => 'kindia',
                'code' => 'GN003',
                'description' => 'Ville agricole, capitale de la Basse-Guinée',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Labé',
                'slug' => 'labe',
                'code' => 'GN004',
                'description' => 'Capitale du Fouta-Djalon, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'N\'Zérékoré',
                'slug' => 'nzerekore',
                'code' => 'GN005',
                'description' => 'Capitale de la Guinée Forestière',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Boké',
                'slug' => 'boke',
                'code' => 'GN006',
                'description' => 'Ville portuaire, centre minier',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Mamou',
                'slug' => 'mamou',
                'code' => 'GN007',
                'description' => 'Ville carrefour, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Faranah',
                'slug' => 'faranah',
                'code' => 'GN008',
                'description' => 'Ville historique, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Kissidougou',
                'slug' => 'kissidougou',
                'code' => 'GN009',
                'description' => 'Ville agricole, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Gueckedou',
                'slug' => 'gueckedou',
                'code' => 'GN010',
                'description' => 'Ville frontalière, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Siguiri',
                'slug' => 'siguiri',
                'code' => 'GN011',
                'description' => 'Ville aurifère, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Kouroussa',
                'slug' => 'kouroussa',
                'code' => 'GN012',
                'description' => 'Ville agricole, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Dabola',
                'slug' => 'dabola',
                'code' => 'GN013',
                'description' => 'Ville de transit, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Dinguiraye',
                'slug' => 'dinguiraye',
                'code' => 'GN014',
                'description' => 'Ville historique, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Tougué',
                'slug' => 'tougue',
                'code' => 'GN015',
                'description' => 'Ville pastorale, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Pita',
                'slug' => 'pita',
                'code' => 'GN016',
                'description' => 'Ville agricole, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Dalaba',
                'slug' => 'dalaba',
                'code' => 'GN017',
                'description' => 'Station climatique, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Lélouma',
                'slug' => 'lelouma',
                'code' => 'GN018',
                'description' => 'Ville rurale, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Mali',
                'slug' => 'mali',
                'code' => 'GN019',
                'description' => 'Ville frontalière, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Gaoual',
                'slug' => 'gaoual',
                'code' => 'GN020',
                'description' => 'Ville rurale, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Koundara',
                'slug' => 'koundara',
                'code' => 'GN021',
                'description' => 'Ville frontalière, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Coyah',
                'slug' => 'coyah',
                'code' => 'GN022',
                'description' => 'Ville périurbaine, Basse-Guinée',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Dubréka',
                'slug' => 'dubreka',
                'code' => 'GN023',
                'description' => 'Ville côtière, Basse-Guinée',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Forécariah',
                'slug' => 'forecariah',
                'code' => 'GN024',
                'description' => 'Ville côtière, Basse-Guinée',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Télimélé',
                'slug' => 'telimele',
                'code' => 'GN025',
                'description' => 'Ville agricole, Moyenne-Guinée',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Boffa',
                'slug' => 'boffa',
                'code' => 'GN026',
                'description' => 'Ville côtière, Basse-Guinée',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Fria',
                'slug' => 'fria',
                'code' => 'GN027',
                'description' => 'Ville industrielle, Basse-Guinée',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Kérouané',
                'slug' => 'kerouane',
                'code' => 'GN028',
                'description' => 'Ville agricole, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Macenta',
                'slug' => 'macenta',
                'code' => 'GN029',
                'description' => 'Ville agricole, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Yomou',
                'slug' => 'yomou',
                'code' => 'GN030',
                'description' => 'Ville frontalière, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Lola',
                'slug' => 'lola',
                'code' => 'GN031',
                'description' => 'Ville frontalière, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Beyla',
                'slug' => 'beyla',
                'code' => 'GN032',
                'description' => 'Ville agricole, Guinée Forestière',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Mandiana',
                'slug' => 'mandiana',
                'code' => 'GN033',
                'description' => 'Ville agricole, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Kérouané',
                'slug' => 'kerouane-2',
                'code' => 'GN034',
                'description' => 'Ville agricole, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Kankan',
                'slug' => 'kankan-2',
                'code' => 'GN035',
                'description' => 'Ville universitaire, Haute-Guinée',
                'is_active' => true,
                'sort_order' => 35,
            ],
        ];

        foreach ($cities as $city) {
            City::create($city);
        }

        $this->command->info('Villes de Guinée créées avec succès !');
    }
}
